
      import {Injectable} from "@angular/core"

      import {HttpClient} from "@angular/common/http";
      import {filter, Observable, of} from "rxjs";
      import  {LogementModel} from "../models/logement.model"

      @Injectable({
        providedIn:'root'
      })

      export class HousingService {



      //?? Recuperation de tous les logement ??cl

      getAllHousing():Observable<LogementModel[]>{
          return of(this.housings)
      }

      //** Recuperation d'un logement par son id **

      getHousingForId(idHousing:number):LogementModel{
        const housing = this.housings.find(housing => housing.id === idHousing);
        if(housing) {
          return housing
        }else {
          throw new Error('Housing not found')
        }
      }

      housings: LogementModel[] = [
        {
        "id": 1,
        "name": "Appartement Luxe",
        "address": "Rue Principale, Paris",
        "telephone": "+33 1 23 45 67 89",
        "cover": "assets/logement/cover/chambre1.jpg",
        "image": ["assets/logement/hotel1.jpg", "assets/logement/hotel2.jpg","assets/logement/hotel3.jpg","assets/logement/hotel4.jpg"],
        "nombre_chambre": 3,
        "star":2,
        "type_lit": ["Queen", "Double"],
        "equipement": ["WiFi", "Télévision", "Cuisine équipée"],
        "nombre_pices": 5,
        "ville": "Paris",
        "isDisponible": true,
        "isApartement": true,
        "isStudio": null,
        "user":"jeam",
        "capacite": "6 personnes",
        "prix": 1200,
        "creatAt": "2024-06-25T12:34:56Z",
        "updateAt": "2024-06-25T12:34:56Z"
      },
      {
        "id": 4,
        "name": "Loft Industriel",
        "address": " Rue des Artisans, Toulouse",
        "telephone": "+33 5 67 89 01 23",
        "cover": "assets/logement/cover/chambre4.jpg",
        "image": ["assets/logement/hotel13.jpg","assets/logement/hotel1.jpg","assets/logement/hotel5.jpg","assets/logement/hotel6.jpg"
        ],
        "nombre_chambre": 2,
        "star": 7,
        "type_lit": ["Queen"],
        "equipement": ["WiFi", "Balcon", "Cuisine équipée"],
        "nombre_pices": 4,
        "user":"Christian",
        "ville": "Toulouse",
        "isDisponible": true,
        "isApartement": true,
        "isStudio": null,
        "capacite": "4 personnes",
        "prix": 1500,
        "creatAt": "2024-06-28T18:45:23Z",
        "updateAt": "2024-06-28T18:45:23Z"
      },
      {
        "id": 3,
        "name": "Maison Familiale",
        "address": "Boulevard de la Liberté, Marseille",
        "telephone": "+33 6 12 34 56 78",
        "cover": "assets/logement/cover/chambre3.jpg",
        "image": ["assets/logement/hotel9.jpg","assets/logement/hotel10.jpg","assets/logement/hotel11.jpg","assets/logement/hotel12.jpg"],
        "nombre_chambre": 4,
        "star":4.5,
        "type_lit": ["King", "Single"],
        "equipement": ["Piscine", "Jardin", "Garage"],
        "nombre_pices": 7,
        "user":"Christian",
        "ville": "Marseille",
        "isDisponible": true,
        "isApartement": null,
        "isStudio": null,
        "capacite": "8 personnes",
        "prix": 2000,
        "creatAt": "2024-06-27T16:12:34Z",
        "updateAt": "2024-06-27T16:12:34Z"
      },
      {
        "id": 2,
        "name": "Studio Moderne",
        "address": " Avenue des Champs, Lyon",
        "telephone": "+33 4 56 78 90 12",
        "cover": "assets/logement/cover/chambre2.jpg",
        "image": ["assets/logement/hotel4.jpg","assets/logement/hotel6.jpg","assets/logement/hotel7.jpg","assets/logement/hotel8.jpg"],
        "nombre_chambre": 1,
        "star":3,
        "type_lit": ["Double"],
        "equipement": ["WiFi", "Climatisation"],
        "nombre_pices": 2,
        "ville": "Lyon",
        "user":"Arnauld",
        "isDisponible": false,
        "isApartement": null,
        "isStudio": true,
        "capacite": "2 personnes",
        "prix": 700,
        "creatAt": "2024-06-26T14:23:45Z",
        "updateAt": "2024-06-26T14:23:45Z"
      },

      {
        "id": 5,
        "name": "Chalet Montagne",
        "address": " Chemin des Alpages, Chamonix",
        "telephone": "+33 4 34 56 78 90",
        "cover": "assets/logement/cover/chambre5.jpg",
        "image": ["assets/logement/hotel10.jpg","assets/logement/hotel7.jpg","assets/logement/hotel4.jpg","assets/logement/hotel6.jpg"],
        "nombre_chambre": 5,
        "star":4.5,
        "type_lit": ["King", "Double", "Single"],
        "equipement": ["Cheminée", "Sauna", "Garage"],
        "nombre_pices": 8,
        "user":"David",
        "ville": "Chamonix",
        "isDisponible": false,
        "isApartement": null,
        "isStudio": null,
        "capacite": "10 personnes",
        "prix": 2500,
        "creatAt": "2024-06-29T20:54:12Z",
        "updateAt": "2024-06-29T20:54:12Z"
      },
      {
        "id": 6,
        "name": "Villa en Bord de Mer",
        "address": " Plage des Palmiers, Nice",
        "telephone": "+33 4 45 67 89 01",
        "cover": "assets/logement/cover/chambre6.jpg",
        "image": ["assets/logement/chambre4.jpg","assets/logement/hotel6.jpg","assets/logement/chambre5.jpg","assets/logement/chambre3.jpg"],
        "nombre_chambre": 6,
        "star":4.6,
        "type_lit": ["King", "Double"],
        "equipement": ["Piscine", "Accès plage privé", "Jacuzzi"],
        "nombre_pices": 10,
        "ville": "Nice",
        "user":"Max",
        "isDisponible": true,
        "isApartement": null,
        "isStudio": null,
        "capacite": "12 personnes",
        "prix": 3000,
        "creatAt": "2024-06-30T10:11:12Z",
        "updateAt": "2024-06-30T10:11:12Z"
      },
      {
        "id": 7,
        "name": "Penthouse de Luxe",
        "address": " Avenue des Lumières, Bordeaux",
        "telephone": "+33 5 56 78 90 23",
        "cover": "assets/logement/cover/chambre7.jpg",
        "image": ["assets/logement/chambre7.jpg","assets/logement/chambre11.jpg","assets/logement/chambre9.jpg","assets/logement/chambre8.jpg"],
        "nombre_chambre": 3,
        "star":4,
        "type_lit": ["Queen", "Single"],
        "equipement": ["WiFi", "Terrasse", "Jacuzzi"],
        "nombre_pices": 5,
        "ville": "Bordeaux",
        "user":"lava .investments",

        "isDisponible": true,
        "isApartement": true,
        "isStudio": null,
        "capacite": "6 personnes",
        "prix": 2200,
        "creatAt": "2024-07-01T14:22:33Z",
        "updateAt": "2024-07-01T14:22:33Z"
      },
      {
        "id": 8,
        "name": "Gîte Rural",
        "address": " Chemin de la Ferme, Bretagne",
        "telephone": "+33 2 78 90 12 34",
        "cover": "assets/logement/cover/chambre8.jpg",
        "image": ["assets/logement/chambre2.jpg","assets/logement/chambre5.jpg","assets/logement/chambre12.jpg","assets/logement/chambre14.jpg"],
        "nombre_chambre": 4,
        "type_lit": ["Double", "Single"],
        "equipement": ["WiFi", "Cheminée", "Jardin"],
        "nombre_pices": 6,
        "ville": "Bretagne",
        "user":"Wilfried",
        "star":5.6,
        "isDisponible": true,
        "isApartement": null,
        "isStudio": null,
        "capacite": "8 personnes",
        "prix": 1800,
        "creatAt": "2024-07-02T11:33:44Z",
        "updateAt": "2024-07-02T11:33:44Z"
      },
      {
        "id": 9,
        "name": "Château Historique",
        "address": " Route du Château, Loire",
        "telephone": "+33 3 89 01 23 45",
        "cover": "assets/logement/cover/chambre9.jpg",
        "image": ["assets/logement/chambre2.jpg","assets/logement/chambre4.jpg","assets/logement/chambre3.jpg","assets/logement/chambre7.jpg"],
        "nombre_chambre": 10,
        "type_lit": ["King", "Queen"],
        "equipement": ["WiFi", "Salle de bal", "Parc"],
        "nombre_pices": 15,
        "star":3,
        "ville": "Loire",
        "user":"Artur souvenir",
        "isDisponible": true,
        "isApartement": null,
        "isStudio": null,
        "capacite": "20 personnes",
        "prix": 5000,
        "creatAt": "2024-07-03T16:44:55Z",
        "updateAt": "2024-07-03T16:44:55Z"
      },
      {
        "id": 10,
        "name": "Maison de Ville",
        "address": "Rue de la République, Lille",
        "telephone": "+33 3 23 45 67 89",
        "cover": "assets/logement/cover/chambre10.jpg",
        "image": ["assets/logement/hotel4.jpg","assets/logement/hotel2.jpg","assets/logement/hotel3.jpg","assets/logement/hotel1.jpg"],
        "nombre_chambre": 3,
        "user":"Michelle . Confort",
        "type_lit": ["Queen", "Double"],
        "equipement": ["WiFi", "Garage", "Balcon"],
        "nombre_pices": 6,
        "star":2,
        "ville": "Lille",
        "isDisponible": true,
        "isApartement": null,
        "isStudio": null,
        "capacite": "6 personnes",
        "prix": 1400,
        "creatAt": "2024-07-04T18:55:11Z",
        "updateAt": "2024-07-04T18:55:11Z"
      },
      {
        "id": 11,
        "name": "Cabane dans les Arbres",
        "address": " Forêt de Brocéliande, Rennes",
        "telephone": "+33 2 34 56 78 90",
        "cover": "assets/logement/cover/chambre11.jpg",
        "image": ["assets/logement/hotel1.jpg","assets/logement/hotel5.jpg","assets/logement/hotel8.jpg","assets/logement/hotel12.jpg"],
        "nombre_chambre": 1,
        "type_lit": ["Double"],
        "equipement": ["WiFi", "Terrasse", "Vue panoramique"],
        "nombre_pices": 3,
        "ville": "Rennes",
        "star": 3,
        "user":"Alex Choco",
        "isDisponible": true,
        "isApartement": null,
        "isStudio": true,
        "capacite": "2 personnes",
        "prix": 900,
        "creatAt": "2024-07-05T20:11:22Z",
        "updateAt": "2024-07-05T20:11:22Z"
      },
      {
        "id": 12,
        "name": "Maison d'Architecte",
        "address": " Avenue des Beaux-Arts, Montpellier",
        "telephone": "+33 4 56 78 90 12",
        "cover": "assets/logement/cover/chambre12.jpg",
        "image": ["assets/logement/hotel4.jpg","assets/logement/hotel6.jpg","assets/logement/hotel8.jpg","assets/logement/hotel10.jpg"],
        "nombre_chambre": 4,
        "type_lit": ["King", "Single"],
        "equipement": ["WiFi", "Piscine", "Jardin"],
        "nombre_pices": 8,
        "star": 4.5,
        "user":"Atanase",
        "ville": "Montpellier",
        "isDisponible": true,
        "isApartement": null,
        "isStudio": null,
        "capacite": "8 personnes",
        "prix": 2500,
        "creatAt": "2024-07-06T22:33:44Z",
        "updateAt": "2024-07-06T22:33:44Z"
      },
      {
        "id": 13,
        "name": "Riad Traditionnel",
        "address": " Medina, Marrakech",
        "telephone": "+212 5 24 45 67 89",
        "cover": "assets/logement/cover/chambre13.jpg",
        "image": ["assets/logement/hotel12.jpg","assets/logement/hotel13.jpg","assets/logement/hotel1.jpg","assets/logement/hotel3.jpg"],
        "nombre_chambre": 5,
        "type_lit": ["Queen", "Double"],
        "equipement": ["WiFi", "Patio", "Cuisine équipée"],
        "nombre_pices": 10,
        "star": 7,
        "user":"Mixe .vision",
        "ville": "Marrakech",
        "isDisponible": true,
        "isApartement": null,
        "isStudio": null,
        "capacite": "10 personnes",
        "prix": 2200,
        "creatAt": "2024-07-07T12:44:55Z",
        "updateAt": "2024-07-07T12:44:55Z"
      },
      {
        "id": 14,
        "name": "Chambre avec Vue",
        "address": " Mont Saint-Michel, Normandie",
        "telephone": "+33 2 56 78 90 12",
        "cover": "assets/logement/cover/chambre14.jpg",
        "image": ["assets/logement/hotel5.jpg","assets/logement/hotel7.jpg","assets/logement/hotel9.jpg","assets/logement/hotel10.jpg"],
        "nombre_chambre": 1,
        "type_lit": ["Double"],
        "equipement": ["WiFi", "Vue sur mer"],
        "nombre_pices": 2,
        "star": 6.5,
        "user":"Dominique pizza",
        "ville": "Normandie",
        "isDisponible": true,
        "isApartement": null,
        "isStudio": true,
        "capacite": "2 personnes",
        "prix": 800,
        "creatAt": "2024-07-08T14:55:11Z",
        "updateAt": "2024-07-08T14:55:11Z"
      },
      {
        "id": 15,
        "name": "Villa Tropicale",
        "address": " Plage de Diamant, Martinique",
        "telephone": "+596 5 96 78 90 12",
        "cover": "assets/logement/cover/chambre15.jpg",
        "image": ["assets/logement/chambre3.jpg", "assets/logement/chambre4.jpg", "assets/logement/chambre4.jpg",
          "assets/logement/chambre14.jpg"
        ],
        "nombre_chambre": 4,
        "type_lit": ["King", "Double"],
        "equipement": ["Piscine", "Jacuzzi", "Jardin tropical"],
        "nombre_pices": 7,
        "ville": "Diamant",
        "star": 3,
        "user":"Micado Ange",
        "isDisponible": true,
        "isApartement": null,
        "isStudio": null,
        "capacite": "8 personnes",
        "prix": 2700,
        "creatAt": "2024-07-09T16:22:33Z",
        "updateAt": "2024-07-09T16:22:33Z"
      }]
    }
